#include "InstrumentExporter.h"
#include "../Synth/SynthEngine.h"

namespace axiom
{

juce::String InstrumentExporter::sampleFileName (int midiNote)
{
    return juce::MidiMessage::getMidiNoteName (midiNote, true, true, 4).replace ("#", "s")
           + "_" + juce::String (midiNote) + ".wav";
}

//==============================================================================
juce::Result InstrumentExporter::exportInstrument (const InstrumentPatch& patch,
                                                   const juce::File& destDir,
                                                   const juce::String& instrumentName,
                                                   const Options& opt,
                                                   std::atomic<float>& progress)
{
    progress = 0.0f;

    const auto safeName = juce::File::createLegalFileName (
        instrumentName.isNotEmpty() ? instrumentName : juce::String ("Axiom Instrument"));

    auto root = destDir.getChildFile (safeName);
    if (! root.createDirectory())
        return juce::Result::fail ("Could not create " + root.getFullPathName());

    // --- Native patch --------------------------------------------------------
    if (opt.writeAxiomPatch)
    {
        auto f = root.getChildFile (safeName + ".axiom");
        if (! f.replaceWithText (patch_io::toJson (patch)))
            return juce::Result::fail ("Could not write " + f.getFullPathName());
    }

    const bool needSamples = opt.writeSfz || opt.writeDecentSampler;
    juce::Array<int> rootNotes;

    if (needSamples)
    {
        auto samplesDir = root.getChildFile ("Samples");
        if (! samplesDir.createDirectory())
            return juce::Result::fail ("Could not create " + samplesDir.getFullPathName());

        for (int note = opt.lowNote; note <= opt.highNote; note += opt.noteStep)
            rootNotes.add (note);

        // Capture the natural release tail, bounded so pads don't explode
        // the export size.
        const double tail = juce::jlimit (0.25, 6.0,
                                          (double) patch.ampEnv.release + (double) patch.fx.reverbMix * 2.0 + 0.25);

        for (int i = 0; i < rootNotes.size(); ++i)
        {
            const int note = rootNotes[i];
            auto audio = SynthEngine::renderNoteOffline (patch, note, 0.79f,
                                                         opt.holdSeconds, tail, opt.sampleRate);

            auto result = writeWav (audio, opt.sampleRate, samplesDir.getChildFile (sampleFileName (note)));
            if (result.failed())
                return result;

            progress = 0.9f * (float) (i + 1) / (float) rootNotes.size();
        }
    }

    if (opt.writeSfz)
    {
        auto f = root.getChildFile (safeName + ".sfz");
        if (! f.replaceWithText (buildSfz (patch, rootNotes, opt.lowNote, opt.highNote)))
            return juce::Result::fail ("Could not write " + f.getFullPathName());
    }

    if (opt.writeDecentSampler)
    {
        auto f = root.getChildFile (safeName + ".dspreset");
        if (! f.replaceWithText (buildDecentSampler (patch, rootNotes, opt.lowNote, opt.highNote)))
            return juce::Result::fail ("Could not write " + f.getFullPathName());
    }

    progress = 1.0f;
    return juce::Result::ok();
}

//==============================================================================
juce::Result InstrumentExporter::writeWav (const juce::AudioBuffer<float>& audio,
                                           double sampleRate, const juce::File& file)
{
    file.deleteFile();
    auto stream = file.createOutputStream();
    if (stream == nullptr)
        return juce::Result::fail ("Could not open " + file.getFullPathName());

    juce::WavAudioFormat format;
    std::unique_ptr<juce::AudioFormatWriter> writer (
        format.createWriterFor (stream.get(), sampleRate,
                                (unsigned int) audio.getNumChannels(), 24, {}, 0));
    if (writer == nullptr)
        return juce::Result::fail ("Could not create WAV writer for " + file.getFileName());

    stream.release();   // writer owns the stream now
    if (! writer->writeFromAudioSampleBuffer (audio, 0, audio.getNumSamples()))
        return juce::Result::fail ("Write failed: " + file.getFileName());

    return juce::Result::ok();
}

//==============================================================================
juce::String InstrumentExporter::buildSfz (const InstrumentPatch& patch,
                                           const juce::Array<int>& rootNotes,
                                           int lowNote, int highNote)
{
    juce::String sfz;
    sfz << "// Generated by Axiom — AI instrument reconstruction\n"
        << "// " << patch_io::describe (patch) << "\n\n"
        << "<control>\ndefault_path=Samples/\n\n"
        << "<group>\n"
        << "ampeg_attack="  << juce::String (patch.ampEnv.attack, 3)  << "\n"
        << "ampeg_decay="   << juce::String (patch.ampEnv.decay, 3)   << "\n"
        << "ampeg_sustain=" << juce::String (patch.ampEnv.sustain * 100.0f, 1) << "\n"
        << "ampeg_release=" << juce::String (patch.ampEnv.release, 3) << "\n\n";

    for (int i = 0; i < rootNotes.size(); ++i)
    {
        const int note = rootNotes[i];
        const int lo   = i == 0 ? lowNote : (rootNotes[i - 1] + note) / 2 + 1;
        const int hi   = i == rootNotes.size() - 1 ? highNote : (note + rootNotes[i + 1]) / 2;

        sfz << "<region> sample=" << sampleFileName (note)
            << " pitch_keycenter=" << note
            << " lokey=" << lo << " hikey=" << hi << "\n";
    }
    return sfz;
}

//==============================================================================
juce::String InstrumentExporter::buildDecentSampler (const InstrumentPatch& patch,
                                                     const juce::Array<int>& rootNotes,
                                                     int lowNote, int highNote)
{
    juce::XmlElement root ("DecentSampler");
    root.setAttribute ("minVersion", "1.0.0");

    auto* groups = root.createNewChildElement ("groups");
    groups->setAttribute ("attack",  (double) patch.ampEnv.attack);
    groups->setAttribute ("decay",   (double) patch.ampEnv.decay);
    groups->setAttribute ("sustain", (double) patch.ampEnv.sustain);
    groups->setAttribute ("release", (double) patch.ampEnv.release);

    auto* group = groups->createNewChildElement ("group");

    for (int i = 0; i < rootNotes.size(); ++i)
    {
        const int note = rootNotes[i];
        const int lo   = i == 0 ? lowNote : (rootNotes[i - 1] + note) / 2 + 1;
        const int hi   = i == rootNotes.size() - 1 ? highNote : (note + rootNotes[i + 1]) / 2;

        auto* sample = group->createNewChildElement ("sample");
        sample->setAttribute ("path",     "Samples/" + sampleFileName (note));
        sample->setAttribute ("rootNote", note);
        sample->setAttribute ("loNote",   lo);
        sample->setAttribute ("hiNote",   hi);
    }

    if (patch.fx.reverbMix > 0.05f)
    {
        auto* effects = root.createNewChildElement ("effects");
        auto* reverb  = effects->createNewChildElement ("effect");
        reverb->setAttribute ("type", "reverb");
        reverb->setAttribute ("wetLevel", (double) patch.fx.reverbMix);
    }

    return root.toString();
}

} // namespace axiom
